import { Professional } from "./types";
export const DEMO_PROFESSIONAL: Professional = {
  id: "demo-maria-gonzalez", nombre: "María González", profesion: "enfermera", especialidad: "Enfermería Domiciliaria",
  bio: "Enfermera licenciada con 8 años de experiencia en atención domiciliaria. Especialista en cuidado de pacientes crónicos, adultos mayores y post-operatorios.",
  slug: "maria-gonzalez", whatsapp: "584125551234", telefono: "+58 212 555 1234", email: "maria.gonzalez@saludpro.com",
  instagram: "@maria.enfermera", direccion: "Av. Principal de Las Mercedes, Caracas", ciudad: "Caracas, Venezuela",
  zonaServicio: "Caracas: Las Mercedes, Chacao, Baruta, El Hatillo, Sucre.", mapsUrl: "https://maps.google.com/?q=Las+Mercedes+Caracas",
  colorAccent: "#0D9488", horarioTexto: "Lunes a Sábado, 7:00 AM - 7:00 PM",
  schedule: [{dia:"Lun",inicio:"07:00",fin:"19:00",activo:true},{dia:"Mar",inicio:"07:00",fin:"19:00",activo:true},{dia:"Mié",inicio:"07:00",fin:"19:00",activo:true},{dia:"Jue",inicio:"07:00",fin:"19:00",activo:true},{dia:"Vie",inicio:"07:00",fin:"19:00",activo:true},{dia:"Sáb",inicio:"08:00",fin:"14:00",activo:true},{dia:"Dom",inicio:"00:00",fin:"00:00",activo:false}],
  servicios: [{id:"s1",nombre:"Inyección intramuscular",descripcion:"Aplicación de inyecciones IM con técnica aséptica y material estéril.",precio:5,duracion:"15 min",unidad:"USD",activo:true},{id:"s2",nombre:"Inyección endovenosa",descripcion:"Aplicación de medicamentos por vía intravenosa.",precio:8,duracion:"20 min",unidad:"USD",activo:true},{id:"s3",nombre:"Cura de heridas",descripcion:"Limpieza, desinfección y vendaje de heridas.",precio:15,duracion:"30 min",unidad:"USD",activo:true},{id:"s4",nombre:"Cuidado de paciente crónico",descripcion:"Atención integral a pacientes encamados o crónicos.",precio:25,duracion:"4 horas",unidad:"USD",activo:true},{id:"s5",nombre:"Toma de muestra de laboratorio",descripcion:"Extracción de sangre para análisis clínicos.",precio:10,duracion:"20 min",unidad:"USD",activo:true},{id:"s6",nombre:"Control de signos vitales",descripcion:"Medición de presión, glucemia, temperatura.",precio:5,duracion:"15 min",unidad:"USD",activo:true}],
  catalogo: [{id:"cat1",titulo:"Cura de herida post-quirúrgica",descripcion:"Paciente con herida quirúrgica. Limpieza profunda, desinfección y vendaje estéril.",precio:15,duracion:"30 min",tags:["cura","heridas","post-quirúrgico"],activo:true},{id:"cat2",titulo:"Cuidado de paciente diabético",descripcion:"Atención integral a paciente diabético con úlceras en pies.",precio:25,duracion:"4 horas",tags:["diabetes","crónico","cuidado"],activo:true},{id:"cat3",titulo:"Toma de muestras a domicilio",descripcion:"Extracción de sangre para análisis clínicos en la comodidad de tu casa.",precio:10,duracion:"20 min",tags:["laboratorio","muestras","domicilio"],activo:true}],
  mostrarServiciosProfesionales: true,
  testimonios: [{id:"t1",nombre:"Carmen R.",rating:5,comentario:"María atendió a mi mamá. Súper profesional, puntual y cariñosa. La recomiendo 100%.",fecha:"Marzo 2026"},{id:"t2",nombre:"José M.",rating:5,comentario:"Necesitaba inyecciones diarias. María llegó siempre puntual. Excelente servicio.",fecha:"Febrero 2026"},{id:"t3",nombre:"Andrea P.",rating:5,comentario:"Cuidó a mi papá post-operatorio. Paciente, atenta y muy preparada.",fecha:"Enero 2026"}],
  certificaciones: [{id:"c1",titulo:"Licenciatura en Enfermería",institucion:"UCV",año:"2017"},{id:"c2",titulo:"Especialización en Cuidados Paliativos",institucion:"Hospital Universitario",año:"2020"},{id:"c3",titulo:"Curso Avanzado de RCP",institucion:"Cruz Roja",año:"2023"},{id:"c4",titulo:"Licencia Colegio de Enfermería",institucion:"Colegio de Enfermeras/os",año:"Vigente"}],
  metodosPago: [{tipo:"pago-movil",datos:{banco:"Banesco",cedula:"V-12.345.678",telefono:"0412-555-1234",titular:"María González"},activo:true},{tipo:"banco",datos:{banco:"Banesco",cuenta:"0134-0000-00-0000000000",titular:"María González",cedula:"V-12.345.678"},activo:true},{tipo:"zelle",datos:{email:"maria.gonzalez@gmail.com",titular:"María González"},activo:true},{tipo:"efectivo",datos:{},activo:true}],
  plan: "trial", trialInicio: Date.now(), trialFin: Date.now() + 15*86400000, activo: true, verificado: true, createdAt: Date.now(), updatedAt: Date.now(),
};
