export interface Parroquia { nombre: string; }
export interface Municipio { nombre: string; parroquias: string[]; }
export interface Estado { nombre: string; municipios: Municipio[]; }
export const VENEZUELA_GEO: Estado[] = [
  { nombre: "Distrito Capital", municipios: [{ nombre: "Libertador", parroquias: ["Altagracia","Candelaria","Catedral","El Paraíso","La Candelaria","San Bernardino","San José","San Juan","Santa Teresa","Sucre","23 de Enero","Coche","Antímano","Caricuao","El Junquito","Macarao"] }] },
  { nombre: "Lara", municipios: [{ nombre: "Iribarren", parroquias: ["Barrio Unión","Buena Vista","Catedral","Concepción","El Cují","Juan de Vargas","La Candelaria","La Pastora","La Rosa","Santa Elena","Santa Teresa","Tamaca","Tintorera","Toribio","Turbio","Unión"] },{ nombre: "Palavecino", parroquias: ["Cabudare","Agua Viva"] },{ nombre: "Torres", parroquias: ["Carora","Camacaro","Castaño","Cedro","Curarigua","Espinoza de los Monteros","Hilario Luna y Luna","Lara","Montañas de Oca","Paraíso","Tricentenario"] },{ nombre: "Morán", parroquias: ["El Jabón","Humocaro Bajo","Humocaro Alto","La Ciénaga","Las Cuibas","Montañas Verdes"] },{ nombre: "Andrés Eloy Blanco", parroquias: ["Sanare","La Cumbre de Sanare","Yacambú"] },{ nombre: "Crespo", parroquias: ["Duparja","Frías","Lara"] },{ nombre: "Jiménez", parroquias: ["Cuara","Diego de Lozada","Paraíso de San José","Tintorera"] },{ nombre: "Simón Planas", parroquias: ["Buria","Sarare"] },{ nombre: "Urdaneta", parroquias: ["Barquisimeto","Cabudare","Siquisique","Santa Inés","Tamaca","El Ujano"] }] },
  { nombre: "Miranda", municipios: [{ nombre: "Baruta", parroquias: ["Baruta","Las Minas","Nuestra Señora del Rosario"] },{ nombre: "Chacao", parroquias: ["Chacao"] },{ nombre: "El Hatillo", parroquias: ["El Hatillo","La Dama","Oriente","Sabana Grande"] },{ nombre: "Sucre", parroquias: ["Petare","Caucagüita","Filas de Mariche","La Dolorita","Leoncio Martínez"] },{ nombre: "Zamora", parroquias: ["Guatire","Bolívar"] },{ nombre: "Plaza", parroquias: ["Guarenas"] },{ nombre: "Guaicaipuro", parroquias: ["Altagracia de La Montaña","Capaya","Cúa","Los Teques","San Pedro","Santa Bárbara","Tácata"] },{ nombre: "Independencia", parroquias: ["Cartanal","Santa Teresa del Tuy"] },{ nombre: "Lander", parroquias: ["Ocumare del Tuy"] },{ nombre: "Brión", parroquias: ["Higuerote","Tacarigua de Brion","Curiepe"] },{ nombre: "Páez", parroquias: ["Río Chico","El Guapo"] }] },
  { nombre: "Zulia", municipios: [{ nombre: "Maracaibo", parroquias: ["Bolívar","Cacique Mara","Caracciolo Parra Pérez","Cecilio Acosta","Chiquinquirá","Coquivacoa","Cristóbal Mora","Francisco Eugenio Bustamante","Idelfonso Vásquez","Juana de Avila","Luis Hurtado Higuera","Manuel Dagnino","Olegario Villalobos","Raúl Leoni","San Isidro","Santa Lucía","Venancio Pulgar"] },{ nombre: "San Francisco", parroquias: ["San Francisco","Los Cortijos","Domitila Flores","Mariano Moreno"] },{ nombre: "Cabimas", parroquias: ["Ambrosio","Carmen Herrera","Jesús Enrique Lossada","La Rosa","Rómulo Betancourt","San Benito"] },{ nombre: "La Cañada de Urdaneta", parroquias: ["La Cañada de Urdaneta","Concepción"] },{ nombre: "Jesús Enrique Lossada", parroquias: ["La Concepción"] },{ nombre: "Mara", parroquias: ["Mara","San Rafael de El Moján","Las Parcelas"] },{ nombre: "Colón", parroquias: ["San Carlos del Zulia","Santa Bárbara de Zulia"] },{ nombre: "Catatumbo", parroquias: ["Encontrados","San Carlos del Zulia"] },{ nombre: "Machiques de Perijá", parroquias: ["Machiques","Río Negro","San José de Perijá"] }] },
  { nombre: "Carabobo", municipios: [{ nombre: "Valencia", parroquias: ["Candelaria","Catedral","El Socorro","Miguel Peña","Negro Primero","Rafael Urdaneta","San Blas","San José","Santa Rosa","Tacarigua"] },{ nombre: "Naguanagua", parroquias: ["Naguanagua"] },{ nombre: "San Diego", parroquias: ["San Diego"] },{ nombre: "Guacara", parroquias: ["Guacara","Miranda","San Joaquín","Yagua"] },{ nombre: "Puerto Cabello", parroquias: ["Bartolomé Salom","Democracia","Fraternidad","Goaigoaza","Puerto Cabello","Raúl Leoni","San Esteban"] },{ nombre: "Los Guayos", parroquias: ["Los Guayos"] },{ nombre: "Libertador", parroquias: ["Tocuyito"] }] },
  { nombre: "Anzoátegui", municipios: [{ nombre: "Sotillo", parroquias: ["Puerto La Cruz","El Chaure","Posadas"] },{ nombre: "Bolívar", parroquias: ["Barcelona","Caigua","El Pilar","Naricual"] },{ nombre: "Anaco", parroquias: ["Anaco","San Joaquín"] },{ nombre: "Guanipa", parroquias: ["El Tigre"] },{ nombre: "Independencia", parroquias: ["Soledad"] },{ nombre: "Miranda", parroquias: ["Píritu","San Francisco"] },{ nombre: "Peñalver", parroquias: ["Puerto Píritu","San Miguel"] }] },
  { nombre: "Táchira", municipios: [{ nombre: "San Cristóbal", parroquias: ["San Cristóbal","Ana María Campos","Cárdenas","La Concordia","Pedro María Morantes","San Juan Bautista"] },{ nombre: "Cárdenas", parroquias: ["Táriba"] },{ nombre: "Junín", parroquias: ["Queniquea","Bramón"] },{ nombre: "Ayacucho", parroquias: ["Coloncito"] },{ nombre: "Bolívar", parroquias: ["San Antonio del Táchira"] }] },
  { nombre: "Mérida", municipios: [{ nombre: "Libertador", parroquias: ["Mérida","El Morro","Gonzalo Picón Febres","Juan Rodríguez Suárez","Lasso de la Vega","Milla","Osorio Rodrigo","Sagrario","San Juan","Santa María"] },{ nombre: "Campo Elías", parroquias: ["Ejido","Acequías","Jají","La Azulita","San José de Surimá"] },{ nombre: "Sucre", parroquias: ["Lagunillas","Chiguará","Estanques"] },{ nombre: "Rangel", parroquias: ["Mucuchíes","Cacute","La Toma","Mucurubá","San Rafael"] },{ nombre: "Tovar", parroquias: ["Tovar","Borotá","El Amparo","El Llano","San Francisco"] }] },
  { nombre: "Aragua", municipios: [{ nombre: "Girardot", parroquias: ["Maracay","Pedro José Ovalles","José Casanova Godoy","Los Tacariguas","Manrique"] },{ nombre: "Mariño", parroquias: ["Turmero"] },{ nombre: "Sucre", parroquias: ["Cagua"] },{ nombre: "Bolívar", parroquias: ["San Joaquín"] },{ nombre: "Libertador", parroquias: ["Palo Negro"] },{ nombre: "Santiago Mariño", parroquias: ["Turmero"] }] },
  { nombre: "Bolívar", municipios: [{ nombre: "Caroní", parroquias: ["San Félix","Unare","Uribe","Vista al Sol","Yocoima","Dalla Costa","Once de Abril","Simón Bolívar"] },{ nombre: "Heres", parroquias: ["Ciudad Bolívar","Agua Salada","Cerro Bolívar","La Sabanita","Marhualla"] },{ nombre: "Piar", parroquias: ["Upata"] }] },
  { nombre: "Falcón", municipios: [{ nombre: "Carirubana", parroquias: ["Norte","Punta Cardón","Santa Ana"] },{ nombre: "Los Taques", parroquias: ["Los Taques"] },{ nombre: "Colina", parroquias: ["La Vela de Coro","Macolla"] }] },
  { nombre: "Sucre", municipios: [{ nombre: "Sucre", parroquias: ["Cumaná","Altagracia","Gran Mariscal","Santa Inés","Valentín Valiente"] },{ nombre: "Bermúdez", parroquias: ["Carúpano","Santa Catalina","Santa Teresa"] },{ nombre: "Ribero", parroquias: ["Cariaco","Río Caribe"] }] },
  { nombre: "Nueva Esparta", municipios: [{ nombre: "Mariño", parroquias: ["Porlamar","Bolívar"] },{ nombre: "Maneiro", parroquias: ["Pampatar","Los Robles"] },{ nombre: "Marcano", parroquias: ["Juan Griego"] }] },
  { nombre: "Vargas", municipios: [{ nombre: "Vargas", parroquias: ["Caraballeda","Caruao","Catia La Mar","El Junko","La Guaira","Los Corales","Maiquetía","Macuto","Naiguatá"] }] },
  { nombre: "Yaracuy", municipios: [{ nombre: "San Felipe", parroquias: ["San Felipe","Albarico","Guama","Páez"] },{ nombre: "Bruzual", parroquias: ["Chivacoa","Campo Elías"] },{ nombre: "Peña", parroquias: ["Yaritagua"] }] },
  { nombre: "Portuguesa", municipios: [{ nombre: "Guanare", parroquias: ["Guanare","Córdoba","San José de la Montaña"] },{ nombre: "Araure", parroquias: ["Araure","Río Acarigua"] },{ nombre: "Páez", parroquias: ["Acarigua"] }] },
  { nombre: "Cojedes", municipios: [{ nombre: "San Carlos", parroquias: ["San Carlos","Juan Ángel Bravo","Manuel Manrique"] },{ nombre: "Tinaquillo", parroquias: ["Tinaquillo"] }] },
  { nombre: "Trujillo", municipios: [{ nombre: "Trujillo", parroquias: ["Trujillo","Carmona","Chachí","El Junco","La Concepción","La Cruz","La Esperanza"] },{ nombre: "Valera", parroquias: ["Valera","Betijoque","Carvajal","La Puerta","Mendoza"] }] },
  { nombre: "Guárico", municipios: [{ nombre: "Juan Germán Roscio", parroquias: ["San Juan de los Morros"] },{ nombre: "Francisco de Miranda", parroquias: ["Calabozo"] }] },
  { nombre: "Delta Amacuro", municipios: [{ nombre: "Tucupita", parroquias: ["Tucupita","San José de Amacuro"] }] },
  { nombre: "Apure", municipios: [{ nombre: "San Fernando", parroquias: ["San Fernando","Biruaca","El Amparo","Pedro Camejo","San Vicente","Santa Rita"] }] },
  { nombre: "Barinas", municipios: [{ nombre: "Barinas", parroquias: ["Barinas","Alto Barinas","Barinitas","El Carmen","Ramón Ignacio Méndez","Rómulo Betancourt","San Antonio","San Silvestre","Santa Lucía","Santa Rita"] }] },
  { nombre: "Monagas", municipios: [{ nombre: "Maturín", parroquias: ["Maturín","Alto de los Godos","Boquerón","Las Cocuizas","Los Godos","San Simón","Santa Cruz","San Vicente"] }] },
  { nombre: "Amazonas", municipios: [{ nombre: "Atures", parroquias: ["Puerto Ayacucho","Fernando Girón Tovar","Parhueña","Platanillal","Samariapo"] }] },
];
export function getEstados(): string[] { return VENEZUELA_GEO.map(e => e.nombre); }
export function getMunicipios(estado: string): string[] { const e = VENEZUELA_GEO.find(e => e.nombre === estado); return e ? e.municipios.map(m => m.nombre) : []; }
export function getParroquias(estado: string, municipio: string): string[] { const e = VENEZUELA_GEO.find(e => e.nombre === estado); if (!e) return []; const m = e.municipios.find(m => m.nombre === municipio); return m ? m.parroquias : []; }
