"use client";
import { useState } from "react";
import { useProfessionalData } from "@/lib/use-professional-data";
import { getProfession } from "@/lib/professions";
import { compressImage } from "@/lib/professionals-service";
import { Save, Loader2, Check, Upload, AlertCircle } from "lucide-react";
export default function ProfilePage() {
  const { professional, loading, saving, guardar, setProfessional } = useProfessionalData();
  const [saved, setSaved] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const handleSave = async (e: React.FormEvent) => { e.preventDefault(); if (!professional) return; const ok = await guardar({ nombre: professional.nombre, especialidad: professional.especialidad, bio: professional.bio, fotoUrl: professional.fotoUrl, whatsapp: professional.whatsapp, telefono: professional.telefono, email: professional.email, instagram: professional.instagram, direccion: professional.direccion, ciudad: professional.ciudad, horarioTexto: professional.horarioTexto, zonaServicio: professional.zonaServicio }); if (ok) { setSaved(true); setTimeout(() => setSaved(false), 3000); } else setError("Error al guardar."); };
  const handlePhoto = async (e: any) => { const f = e.target.files?.[0]; if (!f) return; setUploading(true); try { const url = await compressImage(f); setProfessional(professional ? { ...professional, fotoUrl: url } : null); } catch {} finally { setUploading(false); } };
  if (loading) return <div className="max-w-3xl mx-auto"><div className="glass rounded-2xl p-12 text-center"><Loader2 size={32} className="mx-auto animate-spin text-sp-teal mb-4" /><p className="text-sp-text2 text-sm">Cargando...</p></div></div>;
  if (!professional) return <div className="max-w-3xl mx-auto"><div className="glass rounded-2xl p-12 text-center"><AlertCircle size={32} className="mx-auto text-sp-gold mb-4" /><p className="text-sp-text2 text-sm">No se encontró tu perfil. Contacta: 0422-550-7708</p></div></div>;
  const config = getProfession(professional.profesion); const accent = professional.colorAccent || config.accent;
  const initials = professional.nombre.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase();
  return (
    <div className="max-w-3xl mx-auto overflow-x-hidden">
      <div className="flex items-center gap-3 mb-2"><a href="/admin" className="text-sp-text2 hover:text-white"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M19 12H5M12 19l-7-7 7-7" /></svg></a><h1 className="font-display text-3xl font-bold text-white">Mi Perfil</h1></div>
      <p className="text-sp-text2 text-sm mb-8">Edita la información que verán tus pacientes.</p>
      <form onSubmit={handleSave} className="space-y-6">
        <div className="glass rounded-2xl p-4 sm:p-6 overflow-x-hidden"><label className="block text-xs font-medium text-sp-text2 mb-3 uppercase">Foto profesional</label><div className="flex items-center gap-4"><div className="w-24 h-24 rounded-2xl overflow-hidden flex items-center justify-center flex-shrink-0" style={{ background: `linear-gradient(135deg, ${accent}30 0%, ${accent}10 100%)`, border: `1px solid ${accent}40` }}>{professional.fotoUrl ? <img src={professional.fotoUrl} alt={professional.nombre} className="w-full h-full object-cover" /> : <span className="font-display text-3xl font-bold" style={{ color: accent }}>{initials}</span>}</div><label className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium text-white cursor-pointer" style={{ background: `${accent}30`, border: `1px solid ${accent}50` }}>{uploading ? <Loader2 size={14} className="animate-spin" /> : <Upload size={14} />}{uploading ? "Subiendo..." : "Cambiar foto"}<input type="file" accept="image/*" onChange={handlePhoto} className="hidden" disabled={uploading} /></label></div></div>
        <div className="glass rounded-2xl p-4 sm:p-6 space-y-4 overflow-x-hidden"><div><label className="block text-xs text-sp-text2 mb-2 uppercase">Nombre *</label><input type="text" value={professional.nombre} onChange={(e) => setProfessional({ ...professional, nombre: e.target.value })} required className="w-full max-w-full px-3 py-2.5 rounded-lg text-white outline-none focus:ring-2 focus:ring-sp-teal/50 text-sm" style={{ background: "rgba(6,21,32,0.6)", border: "1px solid rgba(255,255,255,0.1)" }} /></div><div><label className="block text-xs text-sp-text2 mb-2 uppercase">Profesión</label><div className="px-4 py-3 rounded-xl text-sm font-medium flex items-center gap-2" style={{ background: `${accent}15`, border: `1px solid ${accent}40`, color: accent }}><span className="text-lg">{config.emoji}</span><span>{config.label}</span><span className="ml-auto text-[10px] text-sp-text2/60 uppercase">Asignada</span></div></div><div><label className="block text-xs text-sp-text2 mb-2 uppercase">Especialidad</label><input type="text" value={professional.especialidad} onChange={(e) => setProfessional({ ...professional, especialidad: e.target.value })} className="w-full max-w-full px-3 py-2.5 rounded-lg text-white outline-none focus:ring-2 focus:ring-sp-teal/50 text-sm" style={{ background: "rgba(6,21,32,0.6)", border: "1px solid rgba(255,255,255,0.1)" }} /></div><div><label className="block text-xs text-sp-text2 mb-2 uppercase">Biografía</label><textarea value={professional.bio} onChange={(e) => setProfessional({ ...professional, bio: e.target.value })} rows={4} className="w-full max-w-full px-3 py-2.5 rounded-lg text-white outline-none focus:ring-2 focus:ring-sp-teal/50 text-sm resize-none" style={{ background: "rgba(6,21,32,0.6)", border: "1px solid rgba(255,255,255,0.1)" }} /></div></div>
        <div className="glass rounded-2xl p-4 sm:p-6 space-y-4 overflow-x-hidden"><h3 className="text-xs text-sp-text2 uppercase">Contacto</h3><div className="grid grid-cols-1 sm:grid-cols-2 gap-2"><div><label className="block text-xs text-sp-text2 mb-1.5">WhatsApp</label><input type="tel" value={professional.whatsapp} onChange={(e) => setProfessional({ ...professional, whatsapp: e.target.value })} className="w-full max-w-full px-3 py-2.5 rounded-lg text-white outline-none text-sm" style={{ background: "rgba(6,21,32,0.6)", border: "1px solid rgba(255,255,255,0.1)" }} /></div><div><label className="block text-xs text-sp-text2 mb-1.5">Email</label><input type="email" value={professional.email} onChange={(e) => setProfessional({ ...professional, email: e.target.value })} className="w-full max-w-full px-3 py-2.5 rounded-lg text-white outline-none text-sm" style={{ background: "rgba(6,21,32,0.6)", border: "1px solid rgba(255,255,255,0.1)" }} /></div></div></div>
        {error && <div className="p-3 rounded-xl text-sm flex items-center gap-2 text-red-400" style={{ background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.3)" }}><AlertCircle size={16} />{error}</div>}
        <button type="submit" disabled={saving} className="w-full flex items-center justify-center gap-2 px-5 py-3 rounded-xl font-semibold text-white text-sm disabled:opacity-50" style={{ background: `linear-gradient(135deg, ${accent} 0%, ${config.accentLight} 100%)` }}>{saving ? <><Loader2 size={16} className="animate-spin" />Guardando...</> : saved ? <><Check size={16} />Guardado ✓</> : <><Save size={16} />Guardar cambios</>}</button>
      </form>
    </div>
  );
}
