"use client";
import Link from "next/link";
import { useProfessionalData } from "@/lib/use-professional-data";
import { getProfession } from "@/lib/professions";
import { Briefcase, Star, Eye, CreditCard, User, QrCode, ArrowRight, Loader2, Image as ImageIcon } from "lucide-react";
export default function AdminDashboard() {
  const { professional, loading } = useProfessionalData();
  if (loading) return <div className="max-w-6xl mx-auto"><div className="glass rounded-2xl p-12 text-center"><Loader2 size={32} className="mx-auto animate-spin text-sp-teal mb-4" /><p className="text-sp-text2 text-sm">Cargando...</p></div></div>;
  if (!professional) return <div className="max-w-6xl mx-auto"><div className="glass rounded-2xl p-12 text-center"><p className="text-sp-text2 text-sm">No se encontró tu perfil. Contacta: 0422-550-7708</p></div></div>;
  const config = getProfession(professional.profesion); const accent = professional.colorAccent || config.accent;
  const stats = [{label:"Servicios",value:professional.servicios.filter(s=>s.activo).length,color:"#0D9488",icon:Briefcase},{label:"Testimonios",value:professional.testimonios.length,color:"#D4AF37",icon:Star},{label:"Certificaciones",value:professional.certificaciones.length,color:"#06B6D4",icon:Eye},{label:"Pagos",value:professional.metodosPago.filter(m=>m.activo).length,color:"#10B981",icon:CreditCard}];
  return (
    <div className="max-w-6xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8"><div><h1 className="font-display text-3xl font-bold text-white mb-1">Dashboard</h1><p className="text-sp-text2 text-sm">Bienvenido, {professional.nombre.split(" ")[0]} 👋</p></div><Link href={`/c/${professional.slug}`} target="_blank" className="inline-flex items-center gap-2 px-5 py-3 rounded-xl font-semibold text-white text-sm" style={{ background: `linear-gradient(135deg, ${accent} 0%, ${config.accentLight} 100%)` }}><Eye size={16} />Ver portafolio<ArrowRight size={14} /></Link></div>
      <div className="glass rounded-2xl p-6 mb-6"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-2xl flex items-center justify-center flex-shrink-0" style={{ background: `linear-gradient(135deg, ${accent}30 0%, ${accent}10 100%)`, border: `1px solid ${accent}40` }}>{professional.fotoUrl ? <img src={professional.fotoUrl} alt={professional.nombre} className="w-full h-full rounded-2xl object-cover" /> : <span className="font-display text-2xl font-bold" style={{ color: accent }}>{professional.nombre.split(" ").map(w=>w[0]).join("").slice(0,2).toUpperCase()}</span>}</div><div className="flex-1"><h2 className="font-display text-xl font-bold text-white">{professional.nombre}</h2><p className="text-sm text-sp-text2">{professional.especialidad}</p><div className="flex items-center gap-2 mt-1"><span className="px-2 py-0.5 rounded-full text-[10px] font-bold uppercase" style={{ background: `${accent}20`, color: accent }}>{config.label}</span></div></div></div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">{stats.map((s) => <div key={s.label} className="p-5 rounded-2xl" style={{ background: `${s.color}10`, border: `1px solid ${s.color}30` }}><div className="flex items-center justify-between mb-2"><s.icon size={20} color={s.color} /></div><p className="text-3xl font-bold text-white">{s.value}</p><p className="text-xs text-sp-text2 mt-1 uppercase tracking-wider">{s.label}</p></div>)}</div>
      <h2 className="font-display text-lg font-semibold text-white mb-4">Acciones rápidas</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[{href:"/admin/profile",label:"Editar perfil",icon:User,color:"#0D9488"},{href:"/admin/services",label:"Servicios",icon:Briefcase,color:"#06B6D4"},{href:"/admin/servicios-profesionales",label:"Catálogo visual",icon:ImageIcon,color:"#7C3AED"},{href:"/admin/qr",label:"Descargar QR",icon:QrCode,color:"#D4AF37"}].map((a) => <Link key={a.href} href={a.href} className="group p-5 rounded-2xl glass hover-lift"><div className="w-10 h-10 rounded-xl flex items-center justify-center mb-3 transition-transform group-hover:scale-110" style={{ background: `${a.color}20`, border: `1px solid ${a.color}40` }}><a.icon size={18} color={a.color} /></div><h3 className="font-display font-semibold text-white mb-1">{a.label}</h3></Link>)}</div>
    </div>
  );
}
